version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:8.0.32
      volumes:
        - ./mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      networks:
        - keycloak-network

  keycloak:
      image: trannguyenhan/jboss-keycloak
      environment:
        DB_VENDOR: mysql
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password123
      ports:
        - "8180:8080"
      depends_on:
        - mysql
      networks:
        - keycloak-network
      command:
        - "-Dkeycloak.profile.feature.upload_scripts=enabled"

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
