version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2021-10-08T23-58-24Z
    container_name: minio
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server --console-address :9001 /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
